### ISSUE TITLE
Using secret for the database credentials doesn't make their way into the config configmap

### ISSUE THREAD

**Issue by Marck** [TeamPiped/Piped-Kubernetes#157]
### Helm chart version

v3.17.3

### Container name

1337kavin/piped

### Container tag

latest@sha256:759979280703ba11e4069405d21c2fed62a902d135fcea25d76fa13a12f278d7

### Description

When using the Helm chart and using a existing secret, the backend config configmap doesn't reflect the username and password in the secret and always uses these default values from the values.yaml:

```
postgresql:
  enabled: true
  image:
    tag: 13.12.0-debian-11-r58
  auth:
    database: piped
    username: piped
    password: changemepiped
```

### Expected result

I expect that the lookup for the keys in the secret make their way into the backend config.
It seems to me the lookup fails and the Helm install gets the default PostgreSQL auth values in the Piped values.yaml (which are undefined in my values.yaml).

### Helm values to reproduce

**Existing secret (from Sealed Secrets):**
```YAML
apiVersion: v1
data:
  username: cGlwZWQK
  password: dmVyeS1pbnNlY3VyZS1wYXNzd29yZAo=
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: "2025-05-15T13:09:39Z"
  name: piped-database-creds
  namespace: piped
  ownerReferences:
  - apiVersion: bitnami.com/v1alpha1
    controller: true
    kind: SealedSecret
    name: piped-database-creds
    uid: x
  resourceVersion: "x"
  uid: x
type: Opaque
```

**Backend config Piped (a part of it):**
```YAML
backend:
  config:
    database:
      secret:
        name: piped-database-creds
        # Optionally grab differently named keys
        username: username
        password: password
```

**And my PostgreSQL config:**
```YAML
postgresql:
    enabled: true
    image:
      tag: 13.12.0-debian-11-r58
    auth:
      existingSecret: piped-database-creds
```
