### ISSUE TITLE
[piped] Deploying fails when postgres.enabled is false

### ISSUE THREAD

**Issue by MichaelTrip** [TeamPiped/Piped-Kubernetes#29]
### Helm chart name

piped

### Helm chart version

latest

### Container name

n/a

### Container tag

n/a

### Description

Hello,

When i try to deploy the chart with `postgres.enabled: false` i get the following error:

```
Error: INSTALLATION FAILED: template: piped/templates/ytproxy/ingress.yaml:3:19: executing "piped/templates/ytproxy/ingress.yaml" at <include "common.names.fullname" .>: error calling include: template: no template "common.names.fullname" associated with template "gotpl"
```

I have specified the database parameters in the `backend.config` section.

### Expected result

a working piped with a external postgres

### Helm values to reproduce

```YAML
config:
    ...
    database:
     connection_url: jdbc:postgresql://pgsql-cluster-rw.postgres:5432/piped
     driver_class: org.postgresql.Driver
     dialect: org.hibernate.dialect.PostgreSQLDialect
     username: piped-user
     password: randompasswd
     ...
postgresql:
  enabled: false
  image:
    tag: 11.19.0-debian-11-r4
  auth:
    database: piped
    username: piped
    password: changemepiped
```
