### ISSUE TITLE
[piped] Default Helm deployment results in broken setup, misconfiguration?

### ISSUE THREAD

**Issue by aleksasiriski** [TeamPiped/Piped-Kubernetes#3]
### Helm chart name

piped

### Helm chart version

2.0.1

### Container name

frontend

### Container tag

default

### Description

After deploying with Helm to namespace `community` and setting up my Ingresses externally in the same namespace, I can get to the frontend but it results in always loading "Trending" and if I go to preferences it just flashes for a second and then disappears.

![image](https://user-images.githubusercontent.com/31509435/232596018-23c154a7-4dd5-4e56-9e7f-0c4849702257.png)

### Expected result

A working setup or at least something in the logs to point me in the right direction.

### Helm values to reproduce

```YAML
postgresql:
  enabled: false
ingress:
  main:
    enabled: false
  backend:
    enabled: false
  ytproxy:
    enabled: false
frontend:
  env:
    BACKEND_HOSTNAME: pipedapi.piped.mydomain.com
backend:
  config:
    PROXY_PART: https://ytproxy.piped.mydomain.com
    API_URL: https://pipedapi.piped.mydomain.com
    FRONTEND_URL: https://piped.mydomain.com
    COMPROMISED_PASSWORD_CHECK: true
    DISABLE_REGISTRATION: true
    database:
      connection_url: jdbc:postgresql://cloudnative-pg-rw.cnpg-system.svc.cluster.local:5432/piped
      driver_class: org.postgresql.Driver
      dialect: org.hibernate.dialect.PostgreSQLDialect
      username: piped
      password: mypipeddbpassword
```

### Additional Information

Here is my ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: piped
  namespace: community
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entryPoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - "piped.mydomain.com"
    - "*.piped.mydomain.com"
    secretName: piped-mydomain-com
  rules:
  - host: "piped.mydomain.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: piped-frontend
            port:
              number: 80
  - host: "pipedapi.piped.mydomain.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: piped-backend
            port:
              number: 8080
  - host: "ytproxy.piped.mydomain.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: piped-ytproxy
            port:
              number: 8080
```

piped-ytproxy logs:
```sh
Running server!
```

piped-backend logs:
```sh
ThrottlingCache: 0 entries
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
Apr 17, 2023 7:49:35 PM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate ORM core version [WORKING]
Logged in as user: null
Room ID: !CfXSiQMnWTEPfnBNuK:matrix.org
Filter ID: null
Apr 17, 2023 7:49:36 PM org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator initiateService
INFO: HHH000130: Instantiating explicit connection provider: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
Apr 17, 2023 7:49:36 PM org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl logSelectedDialect
INFO: HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
Apr 17, 2023 7:49:38 PM org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator initiateService
INFO: HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
Database connection is ready!
Cleanup: Removed 0 old videos
```

piped-frontend logs:
```sh
2023/04/17 19:49:34 [notice] 1#1: using the "epoll" event method
2023/04/17 19:49:34 [notice] 1#1: nginx/1.23.4
2023/04/17 19:49:34 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2023/04/17 19:49:34 [notice] 1#1: OS: Linux 6.2.9-1-default
2023/04/17 19:49:34 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/04/17 19:49:34 [notice] 1#1: start worker processes
2023/04/17 19:49:34 [notice] 1#1: start worker process 9
2023/04/17 19:49:34 [notice] 1#1: start worker process 10
2023/04/17 19:49:34 [notice] 1#1: start worker process 11
2023/04/17 19:49:34 [notice] 1#1: start worker process 12
10.42.4.9 - - [17/Apr/2023:19:50:48 +0000] "GET /sw.js HTTP/1.1" 200 20950 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0" "myprivateip"
10.42.4.9 - - [17/Apr/2023:19:51:48 +0000] "GET /sw.js HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0" "myprivateip"
```
