### ISSUE TITLE
[Piped] Allow external postgres instance

### ISSUE THREAD

**Issue by cbc02009** [TeamPiped/Piped-Kubernetes#38]
### Helm chart name

Piped

### Describe the solution you'd like

It would be nice if I could use my existing postgres instance with piped, since I have it backed up for disaster recovery scenarios.

**Comment by samip5** [comment]
It should be supported already?

See [values](https://github.com/TeamPiped/Piped-Kubernetes/blob/main/charts/apps/piped/values.yaml#L95L102)

**Comment by JuniorJPDJ** [comment]
It is supported, I'm using it already. I'll show you my values ;)

**Comment by JuniorJPDJ** [comment]
```
      enabled: false

      backend:
        strategy: RollingUpdate
        image:
          pullPolicy: Always
        config:
          database:
            connection_url: jdbc:postgresql://postgres.postgres/piped
            driver_class: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            username: piped
            password: XXXXX

      frontend:
        strategy: RollingUpdate
        image:
          pullPolicy: Always
        env:
          BACKEND_HOSTNAME: api.piped.r00t.party
          NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE: "true"
        resources:
          limits:
            cpu: 4

      ytproxy:
        strategy: RollingUpdate
        image:
          pullPolicy: Always

      ingress:
        main:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          hosts:
            - host: piped.r00t.party
              paths:
                - path: "/"
          tls:
            - hosts:
                - piped.r00t.party
              secretName: piped-cert
        backend:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          ingressClassName: ~
          hosts:
            - host: api.piped.r00t.party
              paths:
                - path: "/"
          tls:
            - hosts:
                - api.piped.r00t.party
              secretName: api-piped-cert
        ytproxy:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          ingressClassName: ~
          hosts:
            - host: ytproxy.piped.r00t.party
              paths:
                - path: "/"
          tls:
            - hosts:
                - ytproxy.piped.r00t.party
              secretName: ytproxy-piped-cert
```
