### ISSUE TITLE
Piped "Failed to construct URL" in Frontend

### ISSUE THREAD

**Issue by 98jan** [TeamPiped/Piped-Kubernetes#64]
### Helm chart name

piped

### Helm chart version

3.0.2

### Container name

1337kavin/piped-frontend

### Container tag

3.0.2

### Description

Configured Domains for frontend, api and ytproxy in the Helm Chart.
When I open the frontend, I get an infinite loading animation and the browser console shows following error messages (see image):

![image](https://github.com/TeamPiped/Piped-Kubernetes/assets/46779261/a15255f5-ae8f-4d28-b451-b75954ee205a)

### Expected result

Application routing works as expected and now error is thrown in Browser console.

### Helm values to reproduce

```YAML
global:
      # -- Set an override for the prefix of the fullname
      nameOverride:
      # -- Set the entire name definition
      fullnameOverride:
      # -- Set additional global labels. Helm templates can be used.
      labels: { }
      # -- Set additional global annotations. Helm templates can be used.
      annotations: { }

    controller:
      # -- enable the controller.
      enabled: false

    serviceAccount:
      create: false


    frontend:
      enabled: true
      service:
        main:
          enabled: true
          primary: true
          type: ClusterIP
          ports:
            http:
              enabled: true
              primary: true
              port: 80
              protocol: HTTP

      image:
        # -- image repository
        repository: 1337kavin/piped-frontend
        # -- image tag
        # @chart.appVersion
        tag:
        # -- image pull policy
        pullPolicy: IfNotPresent

      env:
       BACKEND_HOSTNAME: pipedapi.<domain>

      command: "/bin/ash"
      args:
        - -c
        - "sed -i s/pipedapi.kavin.rocks/$BACKEND_HOSTNAME/g /usr/share/nginx/html/assets/* && /docker-entrypoint.sh nginx -g 'daemon off;'"

      # resources:
      #  requests:
      #    memory: 32Mi
      #  limits:
      #    memory: 128Mi

    backend:
      enabled: true
      service:
        main:
          enabled: true
          primary: true
          type: ClusterIP
          ports:
            http:
              enabled: true
              primary: true
              port: 8080
              protocol: HTTP

      #  command: "/bin/sh"
      #  args:
      #    - -c
      #    - sleep infinity

      # If the hostnames are not set for backend, proxy and API, they will be automatically fetched from their ingresses.
      config:
        PORT: 8080
        HTTP_WORKERS: 2
        # PROXY_PART: https://PROXY_HOSTNAME
        # Outgoing HTTP Proxy - eg: 127.0.0.1:8118
        # HTTP_PROXY: 127.0.0.1:8118
        # Captcha Parameters
        # CAPTCHA_BASE_URL: https://api.capmonster.cloud/
        # CAPTCHA_API_KEY: INSERT_HERE
        API_URL: https://pipedapi.<domain>
        FRONTEND_URL: https://piped.<domain>
        # Enable haveibeenpwned compromised password API
        # COMPROMISED_PASSWORD_CHECK: true
        # Disable Registration
        # DISABLE_REGISTRATION: false
        # Feed Retention Time in Days
        # FEED_RETENTION: 30
        # database:
        # connection_url: jdbc:postgresql://postgres:5432/piped
        # driver_class: org.postgresql.Driver
        # dialect: org.hibernate.dialect.PostgreSQLDialect
        # username: piped
        # password: changeme
        # Please only provide the secret name (it should already exist),
        # it should only include database.username and database.password as others will be taken from above.
        # secret: secret-name


      image:
        # -- image repository
        repository: 1337kavin/piped
        # -- image tag
        # @chart.appVersion
        tag:
        # -- image pull policy
        pullPolicy: IfNotPresent

      # resources:
      #  requests:
      #    memory: 500Mi
      #  limits:
      #    memory: 1500Mi

    ytproxy:
      enabled: true
      service:
        main:
          enabled: true
          primary: true
          type: ClusterIP
          ports:
            http:
              enabled: true
              primary: true
              port: 8080
              protocol: HTTP

      command: "/app/piped-proxy"


      image:
        # -- image repository
        repository: 1337kavin/piped-proxy
        # -- image tag
        # @chart.appVersion
        tag:
        # -- image pull policy
        pullPolicy: IfNotPresent

      # resources:
      #  requests:
      #    memory: 32Mi
      #  limits:
      #    memory: 500Mi

    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: piped.<domain>
            paths:
              - path: "/"
        tls:
        - hosts:
          - piped.<domain>
          secretName: tls-piped


      backend:
        enabled: true
        ingressClassName: nginx
        primary: false
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: pipedapi.<domain>
            paths:
              - path: "/"
        tls:
        - hosts:
          - pipedapi.<domain>
          secretName: tls-pipedapi

      ytproxy:
        enabled: true
        ingressClassName: nginx
        primary: false
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: ytproxy.<domain>
            paths:
              - path: "/"
        tls:
        - hosts:
          - ytproxy.<domain>
          secretName: tls-piped-ytproxy

    # See options from https://artifacthub.io/packages/helm/bitnami/postgresql#parameters
    postgresql:
      enabled: true
      image:
        tag: 13.12.0-debian-11-r58
      auth:
        database: piped
        username: piped
        password: changemepiped

    # -- Probe configuration
    # -- [[ref]](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
    # @default -- See below
    probes:
      # -- Liveness probe configuration
      # @default -- See below
      liveness:
        # -- Enable the liveness probe
        enabled: true
        # -- Set this to `true` if you wish to specify your own livenessProbe
        custom: false
        # -- The spec field contains the values for the default livenessProbe.
        # If you selected `custom: true`, this field holds the definition of the livenessProbe.
        # @default -- See below
        spec:
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3

      # -- Redainess probe configuration
      # @default -- See below
      readiness:
        # -- Enable the readiness probe
        enabled: true
        # -- Set this to `true` if you wish to specify your own readinessProbe
        custom: false
        # -- The spec field contains the values for the default readinessProbe.
        # If you selected `custom: true`, this field holds the definition of the readinessProbe.
        # @default -- See below
        spec:
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3

      # -- Startup probe configuration
      # @default -- See below
      startup:
        # -- Enable the startup probe
        enabled: true
        # -- Set this to `true` if you wish to specify your own startupProbe
        custom: false
        # -- The spec field contains the values for the default startupProbe.
        # If you selected `custom: true`, this field holds the definition of the startupProbe.
        # @default -- See below
        spec:
          initialDelaySeconds: 0
          timeoutSeconds: 1
          ## This means it has a maximum of 5*30=150 seconds to start up before it fails
          periodSeconds: 5
          failureThreshold: 30

    termination:
      gracePeriodSeconds:
```

### Additional Information

- Kubernetes Version 1.28.0
- Flux v2 for deplyoment is used

### Repo link

no public repo available

**Comment by samip5** [comment]
I think setting the `API_URL` and `FRONTEND_URL` in the backend config is screwing it up. I have it working perfectly fine when I have just:

```yaml
config:
  PORT: 8080
  NUM_WORKERS: 2
  PROXY_PART: https://proxy.<snip>
  #DISABLE_REGISTRATION: true
  database:
    connection_url: jdbc:postgresql://postgres-default-rw.database.svc.cluster.local/piped
    secret: *secret
```
