### ISSUE TITLE
[<chart name>] Concise description of the issue

### ISSUE THREAD

**Issue by julienym** [TeamPiped/Piped-Kubernetes#70]
### Helm chart name

piped

### Helm chart version

4.1.0

### Container name

front?

### Container tag

latest

### Description

Seam like something is wrong in my setup?

Page load with multiple hostname query to https://piped-api/...
Example: 	https://piped-api/trending?region=US

### Expected result

Would be expecting my api ingress to be used

### Helm values to reproduce

```YAML
ingress:
        main:
          annotations:
            cert-manager.io/cluster-issuer: ca-issuer
          hosts:
            - host: piped.tools.mgt
              paths:
                - path: "/"
          tls:
            - hosts:
              - piped.tools.mgt
              secretName: piped-main-ingress-cert
        backend:
          annotations:
            cert-manager.io/cluster-issuer: ca-issuer
          hosts:
            - host: piped-api.tools.mgt
              paths:
                - path: "/"
          tls:
            - hosts:
              - piped-api.tools.mgt
              secretName: piped-api-ingress-cert
        ytproxy:
          annotations:
            cert-manager.io/cluster-issuer: ca-issuer
          hosts:
            - host: piped-proxy.tools.mgt
              paths:
                - path: "/"
          tls:
            - hosts:
              - piped-proxy.tools.mgt
              secretName: piped-proxy-ingress-cert
      frontend:
        env:
          BACKEND_HOSTNAME: piped-api.tools.mgt
      backend:
        config:
          HTTP_WORKERS: 2
          # Outgoing HTTP Proxy - eg: 127.0.0.1:8118
          HTTP_PROXY: 192.168.102.1:3128
          # Captcha Parameters
          # CAPTCHA_BASE_URL: https://api.capmonster.cloud/
          # CAPTCHA_API_KEY: INSERT_HERE
          # Enable haveibeenpwned compromised password API
          COMPROMISED_PASSWORD_CHECK: false
          # Disable Registration
          DISABLE_REGISTRATION: false
          # Feed Retention Time in Days
          FEED_RETENTION: 30
          database:
            connection_url: jdbc:postgresql://piped-postgresql:5432/piped
            # driver_class: org.postgresql.Driver
            username: piped
            password: changemepiped
            # Please only provide the secret name (it should already exist),
            # it should only include database.username and database.password as others will be taken from above.
            # secret: secret-name
```
